branches:
  only:
    - sources
install:
  - rm -rf public || exit 0
script:
  - binaries/hugo version
  - binaries/hugo
  - binaries/hugo gen chromastyles --style=github > public/css/syntax.css
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  local_dir: public
  on:
    branch: sources
